name: matrix-hue
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: ""
        type: SECRET
